<a href="https://colab.research.google.com/github/ProgrammerDavid1/Data-Analysis/blob/main/Data%20Analyze%202)%20Numpy%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터분석프로그래밍 4주차 실습

## 실습 시작 전 유의사항

※ 반드시 상단 메뉴에서 '**파일 - 드라이브에 사본 저장**' 진행 후 시작하세요.

## 실습 개요
- Python 자료구조
  - 리스트 인덱싱과 슬라이싱
  - 2차원 리스트의 슬라이싱
- Numpy Array
  - Numpy의 슬라이싱
  - array와 list의 연산 차이
  - Boolean Indexing
  - 크기 조절하기

---

## 리스트 인덱싱과 슬라이싱
리스트의 원하는 요소에 접근하기 위해 인덱스를 사용하는 방법을 실습해보겠습니다.\
**`array[1]`**처럼 하나의 인덱스로 접근하는 것을 **인덱싱**,\
**`array[1:3]`**처럼 여러 개의 인덱스로 특정 범위에 접근하는 것을 **슬라이싱**이라고 합니다.

**알아두면 좋은 정보)**
- 음의 인덱스는 리스트를 뒤집은 방향으로 접근시켜주는 역할을 한다.\
  ex) **`array[-2:]`** : 리스트의 맨 뒤 2개만 추출

- **`array[0:10:2]`**처럼 숫자를 하나 더 추가하면 몇 칸씩 건너 뛰어서 추출할 지 step을 정해줄 수 있다.

<br>

---
**TODO)**

다음 설명을 읽고 split_list 함수를 구현해봅시다.
```
split_list(array) 함수는 임의의 리스트 array를 매개변수로 받아서
맨 처음 값과 맨 마지막 값, 그리고 나머지 중간 값으로 분리해주는 함수입니다.

예시)
array = [a, b, c, d, e]
result = split_list(array)

-> result: a, [b, c, d], e
```

In [ ]:
def split_list(array):
  first_element = array[0]
  last_element = array[-1]
  middle_element = array[1:-1]

  return first_element, middle_element, last_element

In [ ]:
# 함수의 결과값을 하나의 변수(result)에 받는 경우
array_5 = [1, 2, 3, 4, 5]
result = split_list(array_5)
print("함수 결과:", result)
print("result의 타입:", type(result))
print()

# 함수의 결과값을 여러 개의 변수에 받는 경우 (언패킹)
array_ab = ['a', 'b']
first, middle, last = split_list(array_ab)
print("처음 값:", first)
print("중간 값:", middle)
print("마지막 값:", last)
print()

# 불필요한 값을 무시하는 방법
array_7 = [ 1, 2, 3, 4, 5, 6, 7 ]
front, _, back = split_list(array_7)
print("처음 값:", front)
print("마지막 값:", back)

함수 결과: (1, [2, 3, 4], 5)
result의 타입: <class 'tuple'>

처음 값: a
중간 값: []
마지막 값: b

처음 값: 1
마지막 값: 7


## 2차원 리스트의 슬라이싱
arr2D에는 4x4 크기의 **2차원 리스트**가 담겨있습니다.

1차원 리스트 때와 마찬가지로 슬라이싱을 할 수 있지만, 슬라이싱 결과가 똑같이 2차원이어서\
가운데 두 개의 **세로줄**을 가져오기 위해서는 새로운 접근이 필요합니다.

코드 초반부의 arr2D를 출력하는 for문과 출력 결과를 참고하시길 바랍니다.

In [ ]:
arr2D = [[ 0,  1,  1,  0],
         [ 3,  8,  8,  3],
         [ 3,  8,  8,  3],
         [ 0,  1,  1,  0]]

print("원본 리스트: ")
for row in arr2D:
  print(row)
print()

middle_rows = arr2D[ 1:3 ]
print(f"가운데 두 가로줄: {middle_rows}\n")

middle_columns = []
for row in arr2D:
  middle_columns.append(row[1:3])
print(f"가운데 두 세로줄: {middle_columns}\n")

원본 리스트: 
[0, 1, 1, 0]
[3, 8, 8, 3]
[3, 8, 8, 3]
[0, 1, 1, 0]

가운데 두 가로줄: [[3, 8, 8, 3], [3, 8, 8, 3]]

가운데 두 세로줄: [[1, 1], [8, 8], [8, 8], [1, 1]]



## NumPy의 슬라이싱
npArr2D에는 4x4 크기의 **numpy array**가 담겨있습니다.

기본 자료구조 리스트와는 다르게 **동시에 여러 차원의 인덱싱**이 가능해집니다.

리스트에서 특정 행과 특정 열의 값을 가져오려면 arr2D[1][2]과 같이 두 번의 인덱싱을 거쳐야했지만,\
np.array에서는 npArr2D[1, 2]처럼 **콤마**를 통해 한 번에 여러 차원의 접근할 수 있습니다.

이런 방식은 **슬라이싱**도 마찬가지입니다.\
이를 이용해서 궁극적으로는 **중앙 2x2의 값들**을 출력해보도록 합시다.

In [ ]:
import numpy as np

npArr2D = np.array([[ 0,  1,  1,  0],
                    [ 3,  8,  8,  3],
                    [ 3,  8,  8,  3],
                    [ 0,  1,  1,  0]])

print("원본 리스트: ", npArr2D, '', sep='\n')

middle_rows = npArr2D[1:3]
print("가운데 두 가로줄:", middle_rows, '', sep='\n')

middle_columns = npArr2D[ :, 1:3 ]
print("가운데 두 세로줄:", middle_columns, '', sep='\n')

middle_2x2 = npArr2D[ 1:3 , 1:3 ]
print("가운데 2x2 칸:", middle_2x2, '', sep='\n')

원본 리스트: 
[[0 1 1 0]
 [3 8 8 3]
 [3 8 8 3]
 [0 1 1 0]]

가운데 두 가로줄:
[[3 8 8 3]
 [3 8 8 3]]

가운데 두 세로줄:
[[1 1]
 [8 8]
 [8 8]
 [1 1]]

가운데 2x2 칸:
[[8 8]
 [8 8]]



## Numpy array와 list의 연산 차이
Numpy의 array는 list와는 다르게 유용한 연산자들을 제공합니다.

list에서는 할 수 없었던 일들을 가능하게 해주어 여러 복잡한 과정들을 간결하게 해줍니다.


In [ ]:
listA = [1, 2, 3]
listB = [4, 5, 6]

# list와 상수간의 연산
# print(listA + 5) # 불가능
print(listA * 3)

# list와 list간의 연산
print(listA + listB)
# print(listA - listB, listA * listB, listA / listB) # 불가능

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3, 4, 5, 6]


In [ ]:
arrA = np.array([1, 2, 3])
arrB = np.array([4, 5, 6])

# array와 상수간의 연산
print(f'상수 합: {arrA + 5}')
print(f'상수 곱: {arrA * 3}')

# array와 array간의 연산
print(f'array간의 합: {arrA + arrB}')
print(f'array간의 뺄셈: {arrA - arrB}')
print(f'array간의 곱셈: {arrA * arrB}')
print(f'array간의 나눗셈: {arrA / arrB}')

상수 합: [6 7 8]
상수 곱: [3 6 9]
array간의 합: [5 7 9]
array간의 뺄셈: [-3 -3 -3]
array간의 곱셈: [ 4 10 18]
array간의 나눗셈: [0.25 0.4  0.5 ]


## Numpy array의 Boolean Indexing
array는 위의 산술 연산자 뿐만 아니라 논리 연산자도 사용할 수 있습니다.

논리 연산의 결과로는 True와 False로 이뤄진 array가 생길 것입니다.

In [ ]:
import numpy as np

npArr = np.array([3, 6, 10, 2, 5, 9, 7, 11])

mask_even = npArr % 2 == 0
print("각 요소가 짝수인지 여부:", mask_even)

각 요소가 짝수인지 여부: [False  True  True  True False False False False]


이것을 일종의 마스크(필터)처럼 이용하면 array의 특정 값만 뽑아낼 수 있습니다.\
이를 boolean 값을 이용한 인덱싱이라고 하여, Boolean Indexing이라고 부릅니다.

해당 실습에서, 각각의 값이 짝수가 맞는지를 나타내는 마스크를 만들어보고,\
그 마스크로 인덱싱을 하여 짝수 값들만 뽑아보도록 하겠습니다.

In [ ]:
even_array = npArr[mask_even] #wow 신기하다
print("array의 짝수 값들:", even_array)

array의 짝수 값들: [ 6 10  2]


## 크기 조절하기
array를 이용할 때에는, 때때로 연산을 위해 크기를 조절해야하는 경우가 생깁니다.

해당 실습에서는 array의 크기를 조절할 수 있는 여러 함수들을 소개하겠습니다.

- **`arr.shape`**: arr의 크기를 알려줍니다.

- **`arr.reshape(shape)`**: arr가 shape 크기로 변형된 결과를 반환합니다.\
새로운 shape는 원본 shape에서 변형될 수 있는 값이어야 합니다.

- **`np.resize(arr, shape)`**: arr가 shape 크기로 변경된 결과를 반환합니다.

- **`arr.flatten()`**: 다차원의 arr가 1차원으로 펼쳐진 결과를 반환합니다.

<br>

**알아두면 좋은 정보)**

array의 shape는 특수하게 -1이라는 값을 사용할 수 있습니다.

shape에서 -1 값은 "자동으로 계산되어 채워지는 크기"를 의미합니다.

(2×△) 크기의 array로 만들고 싶은데 △ 값을 모르겠는 경우,\
-1로 채워주면 자동으로 알아내어 채워줍니다.

In [ ]:
import numpy as np

arr = np.array([[ 1,  2,  3,  4,  5,  6 ],
                [ 7,  8,  9, 10, 11, 12]])

print(f'원본:\n{arr}\n')

arr_a = arr.reshape((3, 4))
print(f'3x4 크기로 변형:\n{arr_a}\n') #새로운 shape는 원본 shape에서 변형될 수 있는 값이어야 합니다

#arr_b = arr.reshape((3, 3))   # 불가능

arr_c = np.resize(arr, (3, 3))  #resize는 강제로 만든다
print(f'3x3 크기로 축소:\n{arr_c}\n')

arr_d = np.reshape(arr, (-1, 2))
print(f'△x2 크기로 변형:\n{arr_d}\n')

원본:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

3x4 크기로 변형:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

3x3 크기로 축소:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

△x2 크기로 변형:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]



---

**TODO)**
아래 출력을 보고 코드를 완성해봅시다.

In [ ]:
'''
<정리>
- reshape는 원본 arr의 크기로 만들 수 있을 때 사용. 범위를 넘어가면 오류
- resize는 강제로 변형시키는 것이기 때문에, 범위 넘어가도 상관 x
<문법>
- resize: np.resize(arr,shape)       arr가 shape 크기로 변경된 결과를 반환합니다. 넘파이.resize(arr,변경하고 싶은 크기)
- reshape: arr.reshape(shape)        arr가 shape 크기로 변형된 결과를 반환합니다. arr.reshape(크기)
'''

import numpy as np

arr = np.array([[ 1,  2,  3,  4],
                 [ 5,  6,  7,  8],
                 [ 9, 10, 11, 12]])
print("원본 크기:", arr.shape)
print()

arr1 = np.resize(arr,(4,4))
print(f"4x4로 확장:\n{arr1}\n")

arr2 = np.resize(arr,(2,2,3))   #arr.reshape(2,2,3) 으로 알려주심
print(f"2x2x3 크기로 변형:\n{arr2}\n")

arr3 = arr.reshape(4,-1)
print(f"4x△ 크기로 변형:\n{arr3}\n")

arr4 = arr.flatten()
print(f"flatten:\n{arr4}\n")

arr5 = arr.reshape(-1)
print(f"-1을 이용하여 1차원 array로 변형:\n{arr5}\n")

원본 크기: (3, 4)

4x4로 확장:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]

2x2x3 크기로 변형:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

4x△ 크기로 변형:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

flatten:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

-1을 이용하여 1차원 array로 변형:
[ 1  2  3  4  5  6  7  8  9 10 11 12]



## 실습 종료 전 유의사항

※ 완료 시 우측 상단 프로필 옆 '**공유 - 액세스를 *링크가 있는 모든 사용자*로 전환**' 후 복사한 링크를 이루리 과제 란에 업로드 하세요.

<img src="https://i-cubic-i.notion.site/image/https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2F725049b7-a462-4874-83d3-8d8fc3092f85%2F9e740721-91aa-4643-aeb1-e6c29aa7ff1f%2F%25EC%2595%25A1%25EC%2584%25B8%25EC%258A%25A4_%25EC%2584%25A4%25EC%25A0%2595.png?table=block&id=503f4d91-92ad-4768-a049-e7e926ef5871&spaceId=725049b7-a462-4874-83d3-8d8fc3092f85&width=1030" height=300>

</br>

※ 추가로 상단 메뉴 '**파일 - 다운로드 - .ipynb**' 로 다운로드 후 첨부 파일로 업로드 하세요.

※ 즉, 과제의 텍스트란에는 링크를, 파일 첨부란에는 .ipynb 파일을 제출하십시오.